apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: kong/httpbin:latest
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  type: NodePort
  selector:
    app: testapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapp
  annotations:
    ingress.alb.yc.io/subnets: {{ .Values.subnetId }}
    ingress.alb.yc.io/external-ipv4-address: {{ .Values.IPaddress }}
    ingress.alb.yc.io/group-name: infra-ingress
    ingress.alb.yc.io/security-groups: {{ .Values.securityGroup }}
spec:
  tls:
    - hosts:
        - {{ .Values.domenName }}
      secretName: yc-certmgr-cert-id-{{ .Values.certificateId }}
  rules:
    - host: {{ .Values.domenName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testapp
                port:
                  number: 80