image:
    tag: ENC[AES256_GCM,data:G/WdyJ+xcLSoMtwg5tnPxmbO5DDsZmtRn3miaJSzKRpWVg2apEF5rizXs2L1,iv:NtXF2C4nzqPWMa3P1y3JVX6sybXKjrKhB/Ndu0+kahU=,tag:/N8SxmCAtfkaaXrZgIPpRw==,type:str]
    repository: ENC[AES256_GCM,data:kQWH/S2KgBJ8Z6PKJJIUFjP7cajDxxo9rFPqMZWFRkYSpV9Y2IPSqEAi66dmmiuIozyAi6M/spa3gw==,iv:C3moMXz6Nh0VI39dQcgU8uMLm/ELeN1OyVqqtqz6gu8=,tag:ih9+ramsnhDZlKuPwOAoxQ==,type:str]
ingress:
    #ENC[AES256_GCM,data:QoBmwSQjUw2KEop6ryUWiDRWo+xh1R0Hgg==,iv:UPp0dp6vjrkW7zYTrdTKVkdymzZDoUffROqLTMHKV+I=,tag:fRYjEbsf7xc9/ZxOHW9CRw==,type:comment]
    enabled: ENC[AES256_GCM,data:wuHgPA==,iv:1UolVUAjCWAUsfsUxkL4MTKQJUqPKWcFCu9Za7l1Rio=,tag:Gm5c6dvAASU254tvySBwWg==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:k/J6qXBczwNAYw9co/We4QYcfmw=,iv:E1QLdzt3Rcg/qbrx8hSU86XKhXx5L3sN7ro+W9TK/ic=,tag:dggYDWZNa+yx7t4xi54N+w==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:DG4JP/3VZJvPrqTjxQ==,iv:OpFJ7WFrKHWb8fgFcWIiKURj1tz/QUqyiJP+3mP/Qes=,tag:oWgFwgmapJ6chiZ/oAeYKQ==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:ycXgXn7QLErVogxH,iv:I1N9bp1QZ0LyA/lInxNw5zj74SvmpRA6WKhkk7Tmq8o=,tag:EZkdeNutUPfFKYXLe2AmwQ==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:FbUy9Nrk3f+sW6RqjTSWv3CWaSw=,iv:Y13ofn+C18ps+jeVnrTkUssYVDH9YhwdNgTg03e5trQ=,tag:Gu/pM4bnz52bonFzaojhdQ==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:oQ0HnKdGSuBPGLv52Es17oh6xG58YHmCn5U=,iv:j94Dehl4jUMloDDcQy09LuR7RUkf7JqEbZw4gsVeE2A=,tag:MHpAaB+EdBtuCS46sXrOpQ==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:UQ==,iv:3DI4NhFVEHVwpv7wfpv7yitDVkDK8aBrFi7J3l1HwWw=,tag:0Sb0+JUiJiZFb35p68UGRw==,type:str]
              pathType: ENC[AES256_GCM,data:A2VIb61B0vxwSMnbvdyhXEDdmLKCWg==,iv:yvsGvUqKFdoDF3qDa6k+w813lu0lulTwCXz/VkxTndU=,tag:qtiPTya2Hat02DwOnWcIgQ==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:K6uyQWHGEfamQl/azEZMcBQdyweNgK3lQqU=,iv:UpN0pu9jEFvDiXHK+7s6e9huun5gUQQxTdBTax1+nD0=,tag:bw8VV5c/8pi10a3+DS5PHg==,type:str]
          secretName: ENC[AES256_GCM,data:rFrquT+Cr4T+DBfJPsI7j1H+3h2MEN4NInPpayySQlZoI2ixFN13,iv:JDC6qxPxmBqsj0+zneNK/Ymlic1wuXEdvd16+v/r58Q=,tag:AY17/r+ztxzB94POszZ97Q==,type:str]
service:
    type: ENC[AES256_GCM,data:akXd4l2IJjE=,iv:lLE3d28aUxQwgKk+0z6y/dWBslrITu1Nn6l5FiN2FWs=,tag:umKv1kFVJq5GGAvJgspxfA==,type:str]
    #ENC[AES256_GCM,data:3pmu0Rgg6uiVHazFLT55TgEh21kJvl7pHQ==,iv:bVHuBuoJEjKwche0B+DOrnPvaUkXCWrWg7meY4EaPNM=,tag:xwD30N5fLW6f8WU+xA2tZQ==,type:comment]
    nodePort: ENC[AES256_GCM,data:4+Kyq5A=,iv:6xB/z4ojiQLpgYhbWxIfyBVgVZzi38V/g3h0xAodxGU=,tag:UmCflX+uQLmd71spRZLsNA==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ku8nxg07xggm5udltx86vh9ae78pun3gtej2gzf5jp5l3egjg4kq63mhsn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYW5jWitXbHVybG1XSklC
            TzYvZHFMWGRXSUhKcUdtQjFjUlVGY0x3Z0FnClE5R3NGaVdCMWtSUDlhdWExeW9M
            d2hteTFzNE9iUHB6NE5nM3pObU1ZK00KLS0tIEU1WmpoUVZYdSswNUtHMy9OYXEz
            ekZ1MlFwMHp4RWNmRENIbU1lU1VTVGMKQpHmUHWq5O+ljaMTFDTbbko6PprGDwiJ
            EtZUK5YJIJQGOi4qfg8REozWYj6aCmG2lt1fnZAwPyjYw3Wqr1s4tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T07:38:43Z"
    mac: ENC[AES256_GCM,data:fJLycjxKvINbmThbJ/LsOSg+qiK8IReJAu2Zabs5ZxmHBXY+skAcGYCiC8TpI/cOqpvo9ip7JPlqWnZCy4nfi5NDjCK1UyfcUqGWFmmkP5K5WJxs+ii7fhzLTN8/jsOgBKjRzkRcWfXxE0X4vTh01Ldr5j7cOPEE386ppT+bA+Y=,iv:olUCUFLD/iaA07CrglFtPb4+zvS6i2ms6BUb+UH7ITQ=,tag:D6PqLji5QVP93McdssNGpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
