image:
    tag: ENC[AES256_GCM,data:GVCVPHdQo8Sqlv8wuunMZnS61bGuuatKcHuEmevUSjk8OOQQqqyPedNn+5nw,iv:QqYFp14+7Yfmb+5thrRd0/NXlN8mKTnG56Slr57l/1A=,tag:tH0IL46OJsx1oRJaRwMFXQ==,type:str]
    repository: ENC[AES256_GCM,data:72uz2gerCoFaLsQVhyY1ldAdpjha2OV2uS78OqIGnypl4KnXWD1fW8lm9/YvTT67uawq6FgGfXaGYA==,iv:GnZlxXhc9Khlew1zn06cZd92+V3FJNQkozTdLrxzfj0=,tag:l6BndUhvx0L7id8zd2YbrA==,type:str]
ingress:
    #ENC[AES256_GCM,data:CDicd8eLi04i9OMzt6gVWT10+ZIB/YN7kg==,iv:X8aYRH8oeFFTuA7kLo8KdJ9ATG8mrujLszUoX4u1mvA=,tag:RUES9vRuducKoLzqJIPnFQ==,type:comment]
    enabled: ENC[AES256_GCM,data:UGVQNA==,iv:NSEFgx58glm/n/6PSl9SFlB9ojf1/VysIidaljknUSI=,tag:iVVTNy3R6QkjHX2bonFFzQ==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:ym1w7y2EW8U5Z/ww0vr0sYEJJoU=,iv:ImIBaopAX2DFVtCI/Yrmyp2t5/ooY1SrCZuPIW+htA0=,tag:BHyNEs5s/lqIeFJAjqNaOw==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:DIu/iSMtDsmVfBUl5g==,iv:CKYyJ60oG/gWK8bK1oixzvguybMJXF7tdOLJfXoUHm0=,tag:cbg5dfdJkTsY0XdBmbqBYg==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:dGDVBlAxVvaUJSw7zw==,iv:VgKap6vOaRDUyZcWs/Ekw0BnOHWjT9P/5BOCI4w0ra0=,tag:0LNXLT4bhjwzkMwILCAnBA==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:gthFA65rD6zI+7QGt3pYZPVkiFg=,iv:6Qkmmpe7aE7J7GkBe4BLiMNISJpPw1Aj+Ukcd04xsIY=,tag:utN/9clwHSXdOwvXGqGicA==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:rfDJtxQH5AYmO8byFTCWSniRszoA7r3ybCM=,iv:7GK7XrWrRDrcKatyhz8mb828gK+xvVl4c+X0eZnopiw=,tag:Jr8xnbDSisBxOzKgNV6cEw==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:Vg==,iv:8Tpm3PrgU24FlixseFuEfMfqitbOd/NwsH+hF5AayuE=,tag:PB1xcoV65RJA4sac5Sp9Fg==,type:str]
              pathType: ENC[AES256_GCM,data:AGEgP1SthdxrrvvKHENY0iqUMByVfA==,iv:dCakl5DscH9MxGoWf6g/3CrBE4Jl3GUQxS2Mv+aFxLg=,tag:COwiXWALPpWnbQYNm7J1LQ==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:KR5UMlx4xOG5utXoJ9M3ZbbOoy44PqOd9HY=,iv:TplwF3hh2oWLE4g0t1Yh0hDtQDYcf0YaYcUPpjrdhFE=,tag:ExRHpuIkD3Y0k9BtYZAO7A==,type:str]
          secretName: ENC[AES256_GCM,data:wZop8DontMEwkHmxduutXndR/DoRVCoPF9CoxLntGck/Fdisv4f+,iv:o48YrLbaEbvp9t02nntjegxqOlyhWufaIEwo2qTH2gs=,tag:uxjUZ+/qeHFxUO5451YlrA==,type:str]
service:
    type: ENC[AES256_GCM,data:rzFbBg7tYxE=,iv:o0Zhq3rIb3+uyu5+jJ760SyCptf+MD19EcXrUV8KEMM=,tag:AZYvU9NnljnAnHcgQ820Tw==,type:str]
    #ENC[AES256_GCM,data:obN0aq2/ZhTI4s166OlmaNEHp7EpptXOMA==,iv:AV49K9NTevgp/JlHmRf2HDkgjHaJjQ1drxJtW8O2fuI=,tag:s51kM3lkKYx/nIGqZrHn3A==,type:comment]
    nodePort: ENC[AES256_GCM,data:ue1AXCw=,iv:2aDILRnx2SR6BOmW7U3CuMhRaRv7aDpEivrtYkhFgDA=,tag:6/Nxi1QBE3fjX08D9e/zdg==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ku8nxg07xggm5udltx86vh9ae78pun3gtej2gzf5jp5l3egjg4kq63mhsn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOXVOaFR4Njhoa1N5VWZQ
            SlVBNlhNZFErYXlSdmVjVkc0UW53U29jMVNZCk0rRWQ5RkcycTRJeHdvY3k2Q0pw
            dTJxNnZjNlZjTDVPTmovak1WSEVraUkKLS0tIFNScE53UStxTnU5c1lVeXk1YUxU
            UExDaU1JbnRXZG9mSlNhVGZ0bHJ4VG8KSndfjC54Nuk9VfBhdJqWOV4HAuIx2mbw
            N3PFSCZzId3WLpNADmH1LUECMZzQdXxC7CgFrn/hUH+VnUT8CYaeKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T08:12:23Z"
    mac: ENC[AES256_GCM,data:tAbbod3hvkY7ZD1hm6XE/lOzIaxj0PPEkn/vMq0rxIEujw8uWBtkC/k42Y4aJ3Ss20zFz90wohIOAIyxes5EtV/HSvS/Jo5RPA/ioTrOnRXE01nAXtyaIft+EU0WeY3pEEgrgdwCRgSo+qfWRM4PNoy0fpGdfZE9e58qzIgfp58=,iv:eofXMJXE/7+Pdt6XDrUtmM3VhHgTS4XLJNAlyvHF/Lk=,tag:9hDYUtg6/C3VoYhVI3tfZw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
