image:
    repository: ENC[AES256_GCM,data:3ylo//MptN/pSwHDPGjlfr2rFJu9OpSnNg6CCfiWC90IblfbFBv09K2Slv18sXaVotPeVhfD2QkS,iv:PyuEtGqMi1ntA9lcX7nuMM4LR/fWAjsCTK1qhqj0dJY=,tag:FT0VK7ah+YqeAQwmrntJ4w==,type:str]
    tag: ENC[AES256_GCM,data:FF5YmLuNspWGWpjm+ZP7rCpEYzBrMpL2c/0wcml/immu4/ybxIOXKJbczYmR,iv:Y90iUn1kQu+vKeQPj1StSqfh/92hItDNpfxcjevA72k=,tag:8rhw+Nq9OjR0ZomhYSvu0Q==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:QVjfWw==,iv:BC4N7d7yCa6BAGpcOblsYdGFFwc01s/VqMfKq+Tg3Nc=,tag:yhgYnuNDilx9vTDpYCAIGw==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:LGoFhpK9uiH6yYBd62CglHUsvlg=,iv:7hbfhTspIGlGKtpAJFqQujneaPlPltUxXu7aQp+mpX0=,tag:E4dzp43hGp/iW2zckFGB5w==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:GwzzwrDEFS9JVX9Stw==,iv:8t/9vv4hIRJg7gdu7Um9yYa6rEUaddFi/KyfH3/62Bg=,tag:vUNAqskOLvRbWZXp46zdgg==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:gok95G8spAAK4g2p,iv:43pcFC8Z8ZGzp+KdqJTOfRWksv2+wi/l20afjAIQSt0=,tag:lCX2drHy6JngTlQGW1xhag==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:2i80YFNo4nzi1GnFctasdvPulPQ=,iv:a4hfvTjhzgofPV9XhRpUp0hUa1moyUVrgyQj6G8gYbw=,tag:573q1786cl1Rw/HkSk+dSw==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:xyXN9zzOYXp8V4JSnBz+OjLszMxLE/JcHC0=,iv:gdBCs9Nj5puv7Fkb3ZO3hOjvY1+D7R8KLYJn3xneEZk=,tag:7B3FAC0/f61cbuYp9O5/pg==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:WuyJPw==,iv:OnTz83ZGe2e8w1oXfZNMDhgtWi4Oda8WO05Ix568X/w=,tag:Nbx289te6mjDztM1/zHn7w==,type:str]
              pathType: ENC[AES256_GCM,data:/ZHbo5tliIOtg7DovCppq1bg39MuNg==,iv:81YeebhvCQj+r000gXb82OoFigi4Ta/iGAPPfHX0Ihg=,tag:GklPnXZkUf7epjjVQXEEzw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:9/f//V31ziAHE6MS/+JFv/H+oPx+w3Dq+6I=,iv:+LTP3Q4FzTuxy1/cLurRxstnefAIuKir+Dtqhw5atlo=,tag:BB4ynT61jJ6OKqJm/bUgxA==,type:str]
          secretName: ENC[AES256_GCM,data:hOLUbxhhnUaFNCvU+g0xXmX8guN6tHo5SPJiE5s719kIrKJYICQo,iv:h7+g/qfQ5jhdkDvVWo4VJ8929BuPN2mlAtKYLVijSpI=,tag:GPvs4TPRgHpZUpsYgD5MFQ==,type:str]
service:
    type: ENC[AES256_GCM,data:usS+u1PJP8A=,iv:qsFNyu/jKl5io7VlTWTn7vI9IHXt/TnMrBamFucUQGw=,tag:5BKE7b3A886utPtiHjKwXQ==,type:str]
    #ENC[AES256_GCM,data:fy/v+dh2k28cn14usIX5av8BEH31fys+1wXP8w8Hqg4Zy8meZFXAWm6KldJ01fX554//,iv:7QyhWZv3XKhfWDe7quJUR8GOpQgqvZmey7jPR5tm/Yk=,tag:Akv8JSfb2rKc0+F0mvOojg==,type:comment]
    nodePort: ENC[AES256_GCM,data:L30hkVU=,iv:pMeGN7PZb+qat2YiHv4Y55myLikONow4hIZHFqMY1BY=,tag:XHK2ZrctmLk6Dh2UPlWUIQ==,type:int]
env:
    - name: ENC[AES256_GCM,data:Pmmh5qyoew/3Ww==,iv:3eghMWWEUbgTw4f6q1Y+T5l+WEtcMQiRMx7WkPKhmRA=,tag:LBuqPjqOMuA/EkToUHhXHA==,type:str]
      value: ENC[AES256_GCM,data:F4qgOZ2uMA==,iv:vb6Lek1KYNtTS+uEviWN/eT5FijCOTLTV/jEAmaRlNE=,tag:r/IYJI3Ii8N8mBigIoo2/g==,type:str]
    - name: ENC[AES256_GCM,data:X+DIepKFw7nYPA==,iv:w+TZk2mTqaPiu0o9mkg1f85NQPlYo1wsSkCYIEa6iJ4=,tag:mNJnIDefeXlnFHAIeRSyyQ==,type:str]
      value: ENC[AES256_GCM,data:yHtGTRkEkbZ8pXU=,iv:t5hAN5BitiF3OB+PJZFK7pu3aveO0FBGymdW5iwqNXE=,tag:MQe5ZZyM5r7ANmz7yHD5fA==,type:str]
    - name: ENC[AES256_GCM,data:oq2mIcTURLnax5Txah0=,iv:gL8t6xWDL5nKQ61xXB5Xwa5HE6w7MpNWu1FbReyazFU=,tag:dot6FQ25d0oTKx49fmlF6g==,type:str]
      value: ENC[AES256_GCM,data:X+ojQfeupXMLnofa,iv:UoJYYCwkbYYkH7IXQ1+kqekCamRKn7LX4CzVabbM3l8=,tag:LeIq035GjVxCQ/ZTDVUeaw==,type:str]
    - name: ENC[AES256_GCM,data:xEUhjIUQ29iV7Q==,iv:MAUAER1keC9B9uLKyjntFnuUP08WnifOOLggPIC/IXc=,tag:tbErgrD2jKMZAlSbpM5z5w==,type:str]
      value: ENC[AES256_GCM,data:3d6jvlCDR7XdZczxRdA4UwC6wATyQYN2FQWedKFf/xiVMBM806fnRBapmqOG,iv:W2ljlQI4dG4ck+RIuvdPjSk0eWENtTZBrt9b70qq3PY=,tag:WuIyqW4Mx/RJtvCTrDonBA==,type:str]
    - name: ENC[AES256_GCM,data:npdzYCj6OZondw==,iv:CzwJJBUPouQddvytADrEq2kBy6zHZoMEb1azYpibAqg=,tag:TWu+3FNBDdMIyMn67tm7nQ==,type:str]
      value: ENC[AES256_GCM,data:BU3cMg==,iv:1c/EIQv0WICBdZgxCdbhqzNOjHq4QQKtSHreR/O8xjA=,tag:5RVebcKNFhfsu5s7bwvAMA==,type:str]
migrations:
    activeDeadlineSeconds: ENC[AES256_GCM,data:l2Y4,iv:BX1hqpnvJQs8jF2SV+lILtYEJokzNYK08zNGy5n8h9k=,tag:MWUIfMZpm2sOo24tbHdy1Q==,type:int]
    command:
        - ENC[AES256_GCM,data:ndPa1iKt,iv:xueWBF1oWwmNtDJI2O3zdRQxe0TuSK2C3Ls3yX6h0W0=,tag:q9d6wpNQ1NL++OU8CiWAxw==,type:str]
        - ENC[AES256_GCM,data:t4c3e17xOx2s,iv:oOYmlGvMZpdAVz6CujTWLbwT2Z9gW0Hp+uMOXAm6Igc=,tag:V4gq3YuhbjzTSYagGtXH1Q==,type:str]
        - ENC[AES256_GCM,data:dbZgg0jQLA==,iv:7UWlfFH1qKPDQvI/YLE0KzNXX373LeYHYEsFddXMlJ8=,tag:ywI2FvBoXh/MF2R5Fjjevw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ku8nxg07xggm5udltx86vh9ae78pun3gtej2gzf5jp5l3egjg4kq63mhsn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeCtIakVud3ZjWFRsdjMw
            b1pSSlF2UUNzNGlkNC9lZjh1YlB6VWtqRWhVCnJzRG9QclUvUTlwUlB6QSthTG5x
            TWhhR2VRc24wUnY2eG9Ea0xpQmVBdUkKLS0tIDhsRlpXK1lRUXY2U0czVlVvaitX
            dUFwU0ZKUzNsQWMzemd4eEl5ZmdIOFkK+G+Ob4BtdU/LcBVo15LJhyz7tJB26njo
            aQHALH8pnEZPUhrSvnyGYHp/jla+jRAUibTG6hn5AWuptuydhrRQpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T07:38:53Z"
    mac: ENC[AES256_GCM,data:ojgdgmiw54rCb+xzbo5kpq+7eJ4mty1JIINrTy4tZB5+/UBdzSdyuVM7GkC+9l0/oZfbUnnxfzvOOB5Vi6feZp1S+vRoHL6sBRPFB7dJow0fFvc4ahuzM8jPuKHBZeTjiAUJplUSgwELChy/q+FT89RucNOqFriGCM6PhA22sKQ=,iv:VGz7eb7+RDj3i3D9h9Apaow8o3ntScEzuAiinc6yX1U=,tag:FLfh4EnzGgb37g+PR4nGiA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
