image:
    tag: ENC[AES256_GCM,data:zPmrY4NGrzuBRfMBWtS79dUJa9dTRTzQoKT6uEsrEOzmoNsUyKLBot6l7+J8,iv:EyIyfN+ciIL6PjDfzehW765+GXNX3Ax+ycbkAwh6jP8=,tag:6ITzXc0gND/qZ5hVHx9ZaA==,type:str]
    repository: ENC[AES256_GCM,data:NWpAGepCGpYMhLSK0l0oTaD7eHFFgHCnMvU5FNpHJKUcttKrJ0PCUeNdKS4xqNfdcmiFFLWzckfI/Q==,iv:/fW+R22OjStipJ7ObhY+oo67Jo1BmlVSWFoOHicopKA=,tag:rXcI8rUTNOHh/osg53az8A==,type:str]
ingress:
    #ENC[AES256_GCM,data:AdKj8Hfk1+7/8x263tY41XZzaWq3tbGElw==,iv:HdQLlbO4wXa2DhMbt93bn5aREmy1L48ao038Ot5BRss=,tag:kTVKfeCodlkxPxT6eqv2Vw==,type:comment]
    enabled: ENC[AES256_GCM,data:4MDUcQ==,iv:mtkqM6zF6+4aUnnHqpHKrlq3Feu2feECg7XuF/2FUaI=,tag:7nHmFH7rlTDVHIRPXD+8jQ==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:YdE4kpNSNDvFRPerfV1tgfwuy1o=,iv:smhdtDkls+qHiN+tuqnsUJnvwF1WtUZXhBX6HhFaetk=,tag:A5xYq6w8vvr8Nx5vWTrgCA==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:AVM6oNAIbMn0q+soXw==,iv:YG4WSyDDc7+/oo5u4MA60Yb3NjeY+9R8suvDdepEcIs=,tag:oOo5C4j+q7ZrLCvm57m+kg==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:bi66MB4le3JLWI87QA==,iv:tHLks7Vwj0E9IkNzzX3B1pB4KcVOQX9Qz2Nn30qraaI=,tag:ZEdmc3L7krJ7bOyi9OGLGQ==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:VpIQiIqZdBXIVfEVF3P1R4eXJd4=,iv:zParFWLPpZz2xAX7NVrnawRr43EFdcpvfUtgi8pMFds=,tag:PZWnckCxtxMagwAp9uIk7Q==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:MB1e/bPr8zyKst2zhCwVyYYKbaJiK170nSE=,iv:woiWIis2ayUS+8X3TnP4WHBLaF6jbqMatBzytwdlwjk=,tag:1qKzL7WMkIW0dDpeFgmoOQ==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:Ig==,iv:lD7xGKncg3bxwdcuYlXXS1oSgb+PchE2UuPSbV8vyNQ=,tag:fwNhffDU7PX902v9Z8eDVw==,type:str]
              pathType: ENC[AES256_GCM,data:3eZHpiWkuvbdBCn6FKKMQnvhBcyhew==,iv:g/PlKSht8LK6LdaWODQDwdGY8YSolG0TRXp89V3ahs4=,tag:yDHxZORby8GOGVosNDkJyw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:lCJDwO2XZqmQSaFc5fr0HaI/iCjsWRDFn+8=,iv:3Q6DkXtp3UQxmi5yfrKIcSO7AYiDfPWVA4B9ZnNnThQ=,tag:X87awgQOXPs9XIUkii4Kmg==,type:str]
          secretName: ENC[AES256_GCM,data:V0JVo0DINrp+fFUBiG8dxDs1wcZtdzSrgEeryDj8lW2N+saqVokI,iv:PSgywtJEBr/dFV5pVNBxAqBPssvRkI0stD5/KaYUCMI=,tag:4P5ATiadyBFux909KjFBLw==,type:str]
service:
    type: ENC[AES256_GCM,data:NrEfCrYo40k=,iv:hB51Agf/1DfQ1Ml0sMCwgyNVN3k6rjSvup4cLxAEq6k=,tag:q9zw+CrnNJDGIUPnY0M+mQ==,type:str]
    #ENC[AES256_GCM,data:F1sFjVOeuuUYAl4ihF3z3sIL7RCflvt1oA==,iv:8LnbKKlbaLovRdk/4jswbw4pesIKDrRwwhJfhJ7V+oc=,tag:mwdDFIklrjasjenrEkANEg==,type:comment]
    nodePort: ENC[AES256_GCM,data:Ishlrmk=,iv:+U9HF8OO+0tLiFlLtFhiK7/X3VaVGCI1hiIY9fIhqHU=,tag:YJ7ywyPE35LLF5FDWP9LVA==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ku8nxg07xggm5udltx86vh9ae78pun3gtej2gzf5jp5l3egjg4kq63mhsn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVitheUZZUzd5TXZxVXI0
            Vk0rN2VsL2tvMWVzQks2Ty9VRmZBMk5xYlhRCkgzREFPbG1Cay9qcHZtekNtank3
            MTRiRk9veXVzemhpVURHTTJ6NGNicm8KLS0tIEgwVHFDTHYrTDFEc1doUEU0ODNu
            SjNtY0hGYTM2NTZaYmpFWHdmOXZVUlEKZ9lDlko2H6D4UmHUT6b1FKId0I7CS6eO
            kc/CbJA5V5fRmMT3bbmqBU1kM9o/fiByQS5k9AaYB6p3STR9AWvwEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-05T16:05:53Z"
    mac: ENC[AES256_GCM,data:EbXHYmiZ7yHPcC9OPX5ko7r0Wl/2cfBwgEY8IlmVTKsgf6Ula8ZqjRf4xBtNVAAPDMO9h8YhZ8QRlkwGxx6IdjWzSg25JJkh2ckT2bM9IeDlnOFMrcVvzv7K0mJEAhb0VHXeXlpzn16c3W0b5KMPuI7DbiaX6n3ZO150geo8MNM=,iv:YGv1rbjPUDCtLts3rY7VyVnw3zp9F4QwDlCHTasfqls=,tag:jRbq95xZwL1/h0cfSJNxfw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
