image:
    repository: ENC[AES256_GCM,data:BleNprO0UadUNpSJ/yKY4qAV1+T4MLdXzDT86ld8fuSbgdWmJmgnVmwhyfk4rQfT5YWe+hVt1ULY,iv:ajXlwtojpg8BSS7Dt9VfOt4me3pWppHAKLy7HcjWq88=,tag:vWzpptpku210chvouQ0VQA==,type:str]
    tag: ENC[AES256_GCM,data:nZiCXBG+i8mAKJCYmSPAjO9NVmW95pF+wVZ2kNpUMRFOpIfrfyeQglhcIYzV,iv:gIQQ51OZaNY1iNPgLmvYc/GIftmLEuQpF1DMEXFu6AU=,tag:6bFdwSxo3Nqozb14S4pYPw==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:W98CeA==,iv:uGTegVMQzy8rYpj0Ac+du/GIq0ar/CPL8sj2Sn26YRI=,tag:ClaxxuIrTIetwlsF+ICZYA==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:SW0mH3mHW4kJV1Bh1ManTCmyQJE=,iv:6h5qMNddYG4xLXuSVzHbXU/x0OGBQy9+SuN/WB5MHY8=,tag:tJcWEvG4Ci/rNQDxzyMHSg==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:bCfZrnav9AcA6yq99g==,iv:egdfl0XpeBN1q6jPTxsRlRcImLEzvfXP0V6zXLJkkn4=,tag:zz3r42Ypa2XY3n4+nBu1OQ==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:ODWT+LJ9/zIdNUbOKg==,iv:RV2LR6w10eOf/K4LEMekXRUWy2zY75wC1N/ffbEFrTM=,tag:kCgnH5E2w5/qancI2zQNpg==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:a/XA7KCinROfVSS4rAj+PGp7ljg=,iv:HJyUiw/a61q5RM5Vj28NJRMN1eAfnKTgCY6RlcMldBs=,tag:Ot4SkTX7vvvY7k7koRcnlg==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:SNg4VpSRaemt5+KNuBc3uEZhfqpt9HJp/5M=,iv:qLI5gfrGiNbIDOtswtGV58mFoTu8AnYHVEHLMz/xniE=,tag:vW5Et3bqbZ5lXB1QhePyhQ==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:49H0VA==,iv:Z3tBTiortCpdzsUS5wxtm0HWSQb9XcDqWkUxrrbFvy4=,tag:3Cr3wXApbDAIvBkGtDHezA==,type:str]
              pathType: ENC[AES256_GCM,data:A/mIn7WSYimPDD/TuGXh8qz4Z+NsnQ==,iv:+awelC2npI3rn0SA+w16drnI9JIjDt2HEWMVSF/GZCw=,tag:sMwT4b/x417y6zqu6QQ5Uw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:6eJY/V84xwL8HkstmWp6zEMUsiR+XRIwP44=,iv:a6gitfrj1FbtyX3ndlhSfzpyeT2MAIMsDlDB/zcTO4s=,tag:r2IqHUmCx8ENdsJg+RraTw==,type:str]
          secretName: ENC[AES256_GCM,data:njcSZ0xAPCNbqx5s2KbpDnZzyh1lt7qjdjQLtZZujazdZT+xuosp,iv:U3cL/t/yWESQtbFbsO4jhQgvfsmfV+ey03TuXXSi62o=,tag:pX1EvrnsJOZMYJ+GbXVxCw==,type:str]
service:
    type: ENC[AES256_GCM,data:D3lT7ogdNE4=,iv:DT9Cb5u1yIjCqZqKQwXlLq+3PHlA5mchCmGP3g9tD0E=,tag:gzpcojEeE0SUj0jbDjRvxA==,type:str]
    #ENC[AES256_GCM,data:usDqiRpaGM0Hulf/i6TpwNu9eEdaZI0CzV8oytcv+++TXkQgHkaD5Gkws8s4EPA++NsX,iv:IwmmfxLN4YmDSzpBiXo/wXziPTayLNraMLbNGXppfMA=,tag:+nD4JgJJuBxOqzQCMqTHvA==,type:comment]
    nodePort: ENC[AES256_GCM,data:4rBZQNk=,iv:Qon97AsG9GFXUqe1dHk8D7Nk3uy+nsNqGudKb8YavbI=,tag:nRb166KJd3sh9EdOp+4UuQ==,type:int]
env:
    - name: ENC[AES256_GCM,data:X240rdTBwQrdtQ==,iv:/rjY6Nf/bB4sSXCuqN97+NSP6cw1ZQ/07mqv55LaZMQ=,tag:DkFC1d0ZHPEJerUDHc375w==,type:str]
      value: ENC[AES256_GCM,data:lDRS+Mj6VA==,iv:vYEZj2MJfo2bNlCoXgb7tssHObuNz/7T1Zn6i6jvPSc=,tag:gvbp9oeEd5Nk/DTEZ9YZNw==,type:str]
    - name: ENC[AES256_GCM,data:9T7OeexD7kTvZw==,iv:z1OV/rw3fxtQvXVDCgd1N5C4dkBF8ZFFyMcuw1pbOFE=,tag:aV2mZR57idXR+rQORi3KZg==,type:str]
      value: ENC[AES256_GCM,data:t0aT/sT3KZLDbLU=,iv:Q/feYHl1cniPY2MWHSaYLHPmC+vupFWMsF71AUxaJug=,tag:EkPLpgpBgP8AD8RnpKg2ng==,type:str]
    - name: ENC[AES256_GCM,data:DIQYt44gee+PXKL/1DQ=,iv:7+eId91MrK7/jty1zvMYQDkuBEQrbZN7kI0q73lgKHo=,tag:Y0n32mZRb7cIaN3d3MtJXA==,type:str]
      value: ENC[AES256_GCM,data:SiEaB561Bjoc5iBF,iv:Yo+jsHRk2he13056yP3iAYRTHNXORTzsp3bBsamHuGg=,tag:uuPqyIvUXB0Cq2OJqWTJqQ==,type:str]
    - name: ENC[AES256_GCM,data:r4tN0bFCPD3zJA==,iv:2BK62ywUJyasPbXCpsiq8vO/fM1jmJqam/7GDzZUHGM=,tag:499O4XoveUOyFfGLDHzN3w==,type:str]
      value: ENC[AES256_GCM,data:w8L1uTUlJjEF7SmXz9W2Bv7FSARv+ujLB2JDAFpt45wMWYCsMMe+0ua8hOpx,iv:2+2JpaTl8qFDt8i1C+1i2kukylAfSB8xohDkbhETlMk=,tag:E31gx2V/7qjC99xVo6hFWA==,type:str]
    - name: ENC[AES256_GCM,data:lLbstPvDAH/WxA==,iv:rtR+5qs92qmlzyyAt1sjZnwxTEWFlFvLiNnKdIHsO3g=,tag:uyIvaNf7hjpWrKI+U6YIHg==,type:str]
      value: ENC[AES256_GCM,data:MAZIRA==,iv:UsnpAVwULU67KqPQow9hz9FuscPPq380gCAWLqgxhGg=,tag:pKQzKxc9i5qLSUHW3A99eQ==,type:str]
migrations:
    activeDeadlineSeconds: ENC[AES256_GCM,data:60Cu,iv:RL8/paVYf1dR+dhSzTuLzoRbtXF7RgPsYnylPzMkpfY=,tag:JjHN3A9cyMJGZAOascY0eQ==,type:int]
    command:
        - ENC[AES256_GCM,data:Ea2YvkBf,iv:UUG94SrwtYkhm/7jGFUg76lE8tbteIalMttrYVoy2zc=,tag:Snd8f7RcYCWRQ6WV9Ro2lw==,type:str]
        - ENC[AES256_GCM,data:GRsnQWmMxZ3w,iv:PLj5EFAPSPVRZBFgqIVR/AC+erfkP+hovMFzu83id5E=,tag:ipKDx9QQ9zDCd8ik9RVurg==,type:str]
        - ENC[AES256_GCM,data:mwNyLi+doQ==,iv:ulAqZWiYVeLYV02o8/ub3uqVzJrbIzuwWFle+hGkU5E=,tag:yzDJFS4Eg0jNoEx8s1JZiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ku8nxg07xggm5udltx86vh9ae78pun3gtej2gzf5jp5l3egjg4kq63mhsn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFenM4YVVmU2h6MHVUTHBh
            b3NhT1V3VDZTWWVwaDhnTlYrbTlTWlFKbGtjCldvemFBaWo2cFo5K3ovaXkvRkg4
            Vms2ZTh6UVRnOU5rUkZxbXkzSHIrRjgKLS0tIHU4YnZieW1xbWpIc05Xa29PdE53
            czRmQnhXT0NueXBNb3Z5WENIS29DTXcKvUwqML0/Tufq7vFXlfBeA56Ck+/CVONU
            ggYL21l1NtuFA77EC/sMmy+TOelc/TF68flpY/Sw6KRRmroSlFeEnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T08:12:19Z"
    mac: ENC[AES256_GCM,data:n+6n2Iw5Q/JO7uOcOMd5U5cn/RwHuXjJbsuQUPPx2ZGl//705MKsjzcNowbHZ6oLxPk3YHYvvctk/bACz8ncfJEu8uuRQv2y14hHKjSQlRDWVtMIWkgmP1NO+pmiiabkW+9SdkFYX0SHO9BCghfp3o46J8vGS0FS00rGl72JbJc=,iv:yNaFki8h/Fw7wU9cMJMW6Lwshc2ecJxFWolOejrk2yM=,tag:cEYJomUwodmW/JJllABf3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
