image:
    repository: ENC[AES256_GCM,data:zTQJtsHBvfM8V+e0mOzmMsapn90fEOS0Vlc/gISmTRWHw7wrd2Gn/s5ne5Nc0yYOoharrvaccuhi,iv:H+VFOpZWRDUhhOq7MZRpF+lOukvxTXj+jlF/VgXWFvA=,tag:AmFNpi0O1gC7VVaCDktLhA==,type:str]
    tag: ENC[AES256_GCM,data:y5aDnr56egJkzUbU0EkT1+akXqLY4Q2OHkxvmHuOunoqxqtcDRKE9tE6Rsll,iv:YwA80tg7UlwuefH/OPwiFtbDDeLTKG4FiFeKlEzm08w=,tag:PzUV+nxdUyya0PwYVRidhg==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:mjPwBw==,iv:QqQKaVi9SRw9Jc61ldX6S0zsdkFj6f53/rSijuRN3ok=,tag:S2J/ZWT8IexB+Cau8sfDXA==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:cVsEpRoR3Hsvgxm2H2FEnAiJhiY=,iv:Kw/RmkgmzeKoDZoIFBxTcngXX2mLLcMLpPG/ma8ptk0=,tag:+HOZCgsbjiPEwfZ8EjIApA==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:7+icH3tNJZitK68uow==,iv:wglNjcNAaAh3ztQfzL128GDIZaKUl/TCID/czFaRiqA=,tag:RZbMbQMeh0KtlJCCzE2yXg==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:FOz3kMTpr2eK5CyN5A==,iv:r5nLbaY/IaevHJwzX1GmGmZf/xlC8uBu4Xt2MAVhvIc=,tag:qIHcxrxT0erbklWY9XOzzw==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:6n8Jxw+ofq8MBsSn8tjoaObOpts=,iv:7ybtAC8wJMEetcd8W7sgxXwzPVVonoEo4CPsqjUVd9A=,tag:Pbvyawj9xuXPnP3K8zP6Zw==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:wLp0+42Mc5jI1J1M5sFF6VcPJjgTHKOSALA=,iv:OgHdCA1jxp/5lXcYS53hsLopBHcCWIaRJ2swWU4EKB0=,tag:EppMT6/B373L6fEd/2KD0w==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:1am3cQ==,iv:D/Y//yxSpA3vCrERO6xwiSnpiP24moSyUDQyzsV3eeY=,tag:iKtPrMdE8VwwGjwSw5rD+Q==,type:str]
              pathType: ENC[AES256_GCM,data:BeoVDV60J+VzB8P4gh9R/bDksHLyNw==,iv:uPOS/0aihhLzfwZH0Le4ghQKuaJ5Cszud8a3POvRW+s=,tag:Yc+wwqm95XQ+d+5gSMBVOA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:DdxCFRuurrOgj3WLr545LQjBgJ0mJeYEwc8=,iv:0SMan6jvEydOBfN9szJYQ14vEAkMCq2zffzC7MrXWIQ=,tag:o83ktlt2amEZaStt37zNTQ==,type:str]
          secretName: ENC[AES256_GCM,data:pTvJgOF3G86K8IeKCU+RdNi3Tyqh9pBme/fl8HEKRXJ/Glk6IzAt,iv:sjh+LwPOGO4VbH3VDEyRyWzSgO3k09akNFcCrTe3H94=,tag:4ebzXZT78uT2IdQc1OEepQ==,type:str]
service:
    type: ENC[AES256_GCM,data:jwEoRi4qOes=,iv:3EcPtKEs9F2A9qehPxquGJC5I05olJ1TWK9oCzVn3q4=,tag:oqRpp1/00Yp9AMlym/KxjA==,type:str]
    nodePort: ENC[AES256_GCM,data:LmxE0RE=,iv:Resg2vanq7bpyZ8eMZNg1x3mCAX45PA68Y0Ly9lZLZw=,tag:J4EpZSDBRYQW2H8yw9UKJg==,type:int]
env:
    - name: ENC[AES256_GCM,data:ewB2LYX+hlELoQ==,iv:/UaVelLkBop0LFC183F3Jb4uf9RwJ6yrJ9vxyYBlTaU=,tag:lZI4uWEbatdtZg6WO7dYJw==,type:str]
      value: ENC[AES256_GCM,data:SwvXSo25xw==,iv:M2oVlwFzlKtoQXwaqI2heinJgpZgLcnwHmFRCBAsE7E=,tag:XzXM9y+Eo5nzsJdEgGiubQ==,type:str]
    - name: ENC[AES256_GCM,data:EvQCCetTPaMojg==,iv:O7riEuysCDdMq6rJVS+ZXPo//hMkbVtUdyRkYxD1Reo=,tag:tndx7aLgggFnPwOX/uIUqA==,type:str]
      value: ENC[AES256_GCM,data:VGYwGEDujiKMv4o=,iv:w7qbMLd3jKp1LUF5RLW+iZTO5mSZoxVwjRm8sOMoqO0=,tag:ZHp8VQhtprYd1Sv0cfiPkw==,type:str]
    - name: ENC[AES256_GCM,data:BFcbIYFIwJn5KMXyhjA=,iv:tUYTBBfhp8UNP19Cf20fXJkBSErl/hbPDyVIKMjZebE=,tag:r1U+8Fkpklg8OiTGLKOmrA==,type:str]
      value: ENC[AES256_GCM,data:Ch4dOy/KhKQ8ElAZ,iv:iqtmuat3kOVLNkxjalwnWPjOS9EFwYbrwXK/CDRgb4k=,tag:tRV2IXeQwxA7NxXVE+meJg==,type:str]
    - name: ENC[AES256_GCM,data:PsDekRFOwhO9PA==,iv:PWizt8YwHIjJG0vZxU+AymZxLFXbJayb5KlIYpG5d9g=,tag:ikwXOSwOZf1qS1vEH1Xp7Q==,type:str]
      value: ENC[AES256_GCM,data:Q++SCvx7bHlkiDDYKFwPfHeK3fLk+r93aee48nVtgR0vLfFyoErBH8d5ib6u,iv:Nx0y2hdaiOdLQEwCXGscMMldkFrgHdJ9LsB8vRKI5lI=,tag:LaCa1qhmvQGHWeqM+0EQ2A==,type:str]
    - name: ENC[AES256_GCM,data:+dlsJsKsh9iWaw==,iv:Z0k/vWRZGPix2kHwd9WnUVLku5pFq3RHx+PFQzTayGM=,tag:rEdMz5201JDWfAdMoKIaOg==,type:str]
      value: ENC[AES256_GCM,data:WQ3IGQ==,iv:EU64f19iTLguNVneoOQDilgxswA/pqBwRusr3odXMxY=,tag:wd+DGKkxCh50HfIlLIzYig==,type:str]
migrations:
    activeDeadlineSeconds: ENC[AES256_GCM,data:7JKF,iv:1ZlskPr3W0nUSF8zwyFIL7ZVffCIfZeqSFApqiDwKak=,tag:5I2nUQpxmEuSJvq/CmEI9Q==,type:int]
    command:
        - ENC[AES256_GCM,data:D4z65XIt,iv:Mvlt48q+E+/7sCTagXG9+WFRSIzEr20vCcd4L2HLUS8=,tag:6pwzH9XrHrkSvDQWfP06CA==,type:str]
        - ENC[AES256_GCM,data:+mbRD6nsYrBb,iv:Tv1chrBq2GrDlx1+eJNCWfvgi/oq87JPgALtDyl3j1M=,tag:zqikj6wFVLl/upq/SoVRmA==,type:str]
        - ENC[AES256_GCM,data:ayY78ENCvA==,iv:LQg0MyiCffF1RM3wsVVTwOr3sinu1Da3IHrbqhZRmTw=,tag:PsyYrB4Huj8KVKq2w9MeaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ccnczum7snqluqryz5vj0dqhamf79pfmg8aqg39hqxylm5d3vacqk2r5ca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdzhhcTZqQXk5VWw0Z1Nt
            R25XWEtQbFgzMWp2T1hUeVJ5bTQwdEJPVlUwCmwwOU9lNDVGUjdjZ1RRR2h4Nk8r
            bFErYktRUkFHeDVpRDExRW4yRW9WZkUKLS0tIHh1aE52VkVVckh0SEt5dGhVZXZL
            NjdWT0RLOTcvOG4rUzBoUnBVTkt0YWMKzv81YSiVJRJuTzxC5cqWxXNiUT1fWM/9
            3HE0XzWv0cf/cA+a2sB+HsCGmQC0Pp8IsadJsbUhdCoekiIOwwiRMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T14:50:38Z"
    mac: ENC[AES256_GCM,data:dkXlDOJqX+MY5yedhy9xRZzh7V6ML8ncTrZjJwCIOxanvvl2rRpsY7cXHcszrTDw/6Iq9wr8pfeL6kj07RybL8Tc/Q/Ppghp9IWwfyFRawWyiHAdo/UrduMxoOepP2vzjmnHpnpmb6TtS3ojb39xcFxi0jK4sLT/44yyG6BjPc4=,iv:cvXXwXa6Jwv/4a1x528YgnBHpjdpja6WCiMEeu3BADo=,tag:x2oyZN0YFugdULd9zu+x8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
