apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todobackend
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=cr.yandex/crp8eltfp9p1mgq5tb7a/andryplekhanov/todobackend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: todobackend
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: helm/charts/todobackend
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/todobackend.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true